`timescale 1ns / 1ps

// AD9117 DDR output stage: parallel I/Q @122.88 MSa/s/ch -> interleaved DDR bus.
//
// The AD9117 latches the shared DB[13:0] bus on BOTH edges of DCLKIO (DDR):
// I on the rising edge, Q on the falling edge (IRISING=1, IFIRST=1 — the SPI
// 0x02 defaults).  So to reach 122.88 MSa/s/ch the interleaved bus runs at
// 245.76 MSa/s with DCLKIO at 122.88 MHz (< the AD9117 250 MSPS / 125 MHz max).
//
// Each DB bit is driven by an ODDRE1 (UltraScale+) clocked at sys_clk:
//   rising  edge -> I[bit]   (D1)
//   falling edge -> Q[bit]   (D2)
// so one sys_clk period emits the I then the Q nibble -> 245.76 MSa/s.
//
// DCLKIO is generated by an ODDRE1 (D1=1, D2=0) clocked by i_clk_dco, a phase-
// shifted copy of sys_clk.  Its edges must land in the CENTER of the DB data eye
// (AD9117 datasheet Fig 93, tS=0.13/tH=1.1 ns @1.8 V).  The DB eye is ~4.07 ns
// wide (half a 122.88 MHz period); centering the DCLKIO rising edge in the I eye
// means i_clk_dco ~ sys_clk + 90 deg.  PROVISION i_clk_dco as a 90 deg (or
// 270 deg, polarity per IRISING) MMCM output and tighten in Vivado against the
// measured DB->AD9117 setup/hold — the exact phase is a board bring-up step.
//
module tx_ddr_out (
  input  wire        i_clk,      // sys_clk @ 122.88 MHz (DB ODDR clock)
  input  wire        i_clk_dco,  // sys_clk phase-shifted ~90 deg (DCLKIO ODDR clock)
  input  wire        i_rst,      // synchronous reset (active high) for ODDRE1 SR

  input  wire signed [13:0] i_i, // I sample (drives DB on DCLKIO rising)
  input  wire signed [13:0] i_q, // Q sample (drives DB on DCLKIO falling)

  output wire [13:0] o_dac_db,   // -> FPGA_DAC_DB[13:0]
  output wire        o_dac_dclkio// -> FPGA_DAC_DCLKIO
);

  // ===== DB[13:0]: ODDRE1 per bit, D1=I (rising), D2=Q (falling) =====
  genvar b;
  generate
    for (b = 0; b < 14; b = b + 1) begin : g_db
      ODDRE1 #(
        .IS_C_INVERTED (1'b0),
        .IS_D1_INVERTED(1'b0),
        .IS_D2_INVERTED(1'b0),
        .SRVAL         (1'b0)
      ) u_db_oddr (
        .Q  (o_dac_db[b]),
        .C  (i_clk),
        .D1 (i_i[b]),     // launched on rising edge of i_clk
        .D2 (i_q[b]),     // launched on falling edge of i_clk
        .SR (i_rst)
      );
    end
  endgenerate

  // ===== DCLKIO: ODDRE1 emitting a 122.88 MHz clock, phase-centered in DB eye =====
  // D1=1 / D2=0 on i_clk_dco makes a clean half-rate-of-the-bus square wave whose
  // rising edge (I latch) sits mid-I-eye and falling edge (Q latch) sits mid-Q-eye.
  ODDRE1 #(
    .IS_C_INVERTED (1'b0),
    .IS_D1_INVERTED(1'b0),
    .IS_D2_INVERTED(1'b0),
    .SRVAL         (1'b0)
  ) u_dco_oddr (
    .Q  (o_dac_dclkio),
    .C  (i_clk_dco),
    .D1 (1'b1),
    .D2 (1'b0),
    .SR (i_rst)
  );

endmodule
